name: Go Release Automation

on:
  push:
    branches:
      - main  # Triggers on commits to the main branch

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository under $GITHUB_WORKSPACE

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.22'  # Specify the Go version

    - name: Fetch packages
      run : |
        go mod tidy

    - name: Build
      run: |
        GOOS=darwin GOARCH=amd64 go build -o hex

    - name: Prepare release tag
      id: prep
      run: echo "::set-output name=tag::v1.0.0-$(date +'%Y%m%d%H%M%S')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.prep.outputs.tag }}
        release_name: Release ${{ steps.prep.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # This URL is used to upload assets to
        asset_path: ./hex  # Path to the binary file
        asset_name: hex # Name of the binary asset
        asset_content_type: application/octet-stream  # MIME type

